name: Discord Push Logger

on:
  push:

jobs:
  webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Embed
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          DIFF=""

          while read file; do
            [ -z "$file" ] && continue
            DIFF="${DIFF}+ ${file}\n"
          done < <(jq -r '.commits[].added[]?' "$GITHUB_EVENT_PATH")

          while read file; do
            [ -z "$file" ] && continue
            DIFF="${DIFF}+ ${file}\n"
          done < <(jq -r '.commits[].modified[]?' "$GITHUB_EVENT_PATH")

          while read file; do
            [ -z "$file" ] && continue
            DIFF="${DIFF}- ${file}\n"
          done < <(jq -r '.commits[].removed[]?' "$GITHUB_EVENT_PATH")

          COMMIT_MSG=$(jq -r '.head_commit.message' "$GITHUB_EVENT_PATH")
          COMMIT_URL=$(jq -r '.head_commit.url' "$GITHUB_EVENT_PATH")
          AUTHOR=$(jq -r '.sender.login' "$GITHUB_EVENT_PATH")
          REPO=$(jq -r '.repository.full_name' "$GITHUB_EVENT_PATH")
          SHORT_SHA=$(jq -r '.after' "$GITHUB_EVENT_PATH" | cut -c1-7)

          PAYLOAD=$(jq -n \
            --arg repo "$REPO" \
            --arg msg "$COMMIT_MSG" \
            --arg url "$COMMIT_URL" \
            --arg author "$AUTHOR" \
            --arg diff "$DIFF" \
            --arg sha "$SHORT_SHA" \
            '{
              username: "Global | Code Editor",
              embeds: [{
                color: 5814783,
                author: {
                  name: $repo
                },
                description:
                  ("```diff\n" + $diff + "```"),
                fields: [
                  {
                    name: "main",
                    value: $msg
                  }
                ],
                footer: {
                  text: ($sha + " by " + $author)
                },
                url: $url
              }]
            }')

          curl \
            -H "Content-Type: application/json" \
            -X POST \
            -d "$PAYLOAD" \
            "$WEBHOOK"
